### PR TITLE
linter: add linter rule for different case styles and fixes

### LINKED ISSUE #342: Add linter rule for symbols cases

### PR DESCRIPTION
**Pull request by Kaladin13**
Closes #342

### CODE REVIEW

File: crates/tolk-linter/src/rules/ast/camel_case_detector.rs [hunk 1]
```diff
@@ -0,0 +1,260 @@
...
+/// ```
+#[derive(ViolationMetadata)]
+#[violation_metadata(stable_since = "v0.0.1")]
+pub struct CamelCaseDetector;
+
+impl Violation for CamelCaseDetector {
+    const FIX_AVAILABILITY: FixAvailability = FixAvailability::Always;
+
+    fn message(&self) -> String {
+        "Identificator should be camelCase".to_owned()
```
Comment (i582) [inline crates/tolk-linter/src/rules/ast/camel_case_detector.rs]: `name should be camelCase`

File: crates/tolk-linter/src/rules/ast/camel_case_detector.rs [hunk 2]
```diff
@@ -0,0 +1,260 @@
...
+    }
+}
+
+enum CaseRules {
+    LowerCamelCase,
+    UpperCamelCase,
+    ShoutySnakeCase,
```
Comment (i582) [inline crates/tolk-linter/src/rules/ast/camel_case_detector.rs]: https://en.wikipedia.org/wiki/Snake_case

Image

:D

File: crates/tolk-linter/src/rules/ast/camel_case_detector.rs [hunk 3]
```diff
@@ -0,0 +1,260 @@
...
+}
+
+fn fire_diagnostic_by_case(
+    symbol: &Symbol,
+    symbol_id: &SymbolId,
```
Comment (i582) [inline crates/tolk-linter/src/rules/ast/camel_case_detector.rs]: Symbol itself already contains an identifier

File: crates/tolk-linter/src/rules/ast/camel_case_detector.rs [hunk 4]
```diff
@@ -0,0 +1,260 @@
...
+            <str as ToUpperCamelCase>::to_upper_camel_case,
+            "UpperCamelCase",
+        ),
+        CaseRules::ShoutySnakeCase => (
+            <str as ToShoutySnakeCase>::to_shouty_snake_case,
+            "SHOUTY_SNAKE_CASE",
+        ),
+    };
+
+    let correct_case = case_fn(&symbol.name.to_string());
```
Comment (i582) [inline crates/tolk-linter/src/rules/ast/camel_case_detector.rs]: I think the code would be much more readable if we called the transformation function directly inside the match:

```
match case {
    LowerCamelCase => symbol.name.to_lower_camel_case()
    ...
}
```

File: crates/tolk-linter/src/rules/ast/camel_case_detector.rs [hunk 5]
```diff
@@ -0,0 +1,260 @@
...
+    }
+}
+
+enum CaseRules {
+    LowerCamelCase,
+    UpperCamelCase,
+    ShoutySnakeCase,
+}
+
+fn fire_diagnostic_by_case(
```
Comment (i582) [inline crates/tolk-linter/src/rules/ast/camel_case_detector.rs]: t's better to call it `check_case` since it doesn't always fire a diagnostic

File: crates/tolk-linter/src/rules/ast/field_init_can_be_folded.rs [hunk 6]
```diff
@@ -107,6 +107,7 @@ fn fire_diagnostic(
             edits: vec![Edit {
                 span: argument.span(),
                 replacement: key_name,
+                file_id: None,
```
Comment (i582) [inline crates/tolk-linter/src/rules/ast/field_init_can_be_folded.rs]: `file_id: file_id` or just `file_id`

File: crates/tolk-linter/src/rules/ast/mutable_variable_can_be_immutable.rs [hunk 7]
```diff
@@ -82,6 +82,7 @@ pub fn check_file(checker: &mut Checker, file_id: FileId) -> Option<()> {
                 edits: vec![Edit {
                     span: Span::from_syntax(&kind_node),
                     replacement: "val".to_string(),
+                    file_id: None,
```
Comment (i582) [inline crates/tolk-linter/src/rules/ast/mutable_variable_can_be_immutable.rs]: same here

File: crates/tolk-linter/src/rules/ast/unused_variable.rs [hunk 8]
```diff
@@ -115,6 +115,7 @@ fn fire_diagnostic(
                 edits: vec![Edit {
                     span: Span::from_syntax(&ident.0),
                     replacement: format!("_{}", name),
+                    file_id: None,
```
Comment (i582) [inline crates/tolk-linter/src/rules/ast/unused_variable.rs]: same here

File: crates/tolk-linter/src/rules/violation.rs [hunk 9]
```diff
@@ -60,6 +60,7 @@ pub fn code_to_rule(linter: Linter, code: &str) -> Option<(RuleGroup, Rule)> {
         (Tolk, "E006") => unused_import::UnusedImport,
         (Tolk, "E007") => pure_function_call_unused::PureFunctionCallUnused,
         (Tolk, "E008") => no_bounce_handler::NoBounceHandler,
+        (Tolk, "E009") => camel_case_detector::CamelCaseDetector,
```
Comment (i582) [inline crates/tolk-linter/src/rules/violation.rs]: We also have a "snake case", let's call it `NameCaseChecker`

File: crates/tolk-linter/src/lib.rs [hunk 10]
```diff
@@ -181,6 +206,18 @@ impl<'a> Checker<'a> {
             .cloned()
     }
 
+    pub fn get_all_symbol_global_usages(
```
Comment (i582) [inline crates/tolk-linter/src/lib.rs]: `global_usages_of()` for consistency

File: crates/tolk-linter/src/lib.rs [hunk 11]
```diff
@@ -181,6 +206,18 @@ impl<'a> Checker<'a> {
...
+        &self,
+        symbol_id: &SymbolId,
+    ) -> impl Iterator<Item = &NameUse> {
+        self.type_db
+            .project_index
+            .resolved_uses
+            .iter()
+            .map(|v| v.1.global_usages_of(*symbol_id))
```
Comment (i582) [inline crates/tolk-linter/src/lib.rs]: `iter().values().map(|v| v.global_usages_of(*symbol_id))`

File: crates/tolk-linter/src/lib.rs [hunk 12]
```diff
@@ -181,6 +206,18 @@ impl<'a> Checker<'a> {
             .cloned()
     }
 
+    pub fn get_all_symbol_global_usages(
+        &self,
+        symbol_id: &SymbolId,
```
Comment (i582) [inline crates/tolk-linter/src/lib.rs]: `SymbolId` is trivially copyable (just 8 bytes), no need to pass it by reference

File: crates/tolk-linter/Cargo.toml [hunk 13]
```diff
@@ -23,6 +23,7 @@ thiserror = { workspace = true }
 log = { workspace = true }
 rustc-hash = { workspace = true }
 memchr = { workspace = true }
+heck = { workspace = true }
```
Comment (i582) [inline crates/tolk-linter/Cargo.toml:26]: what the heck?

File: crates/tolk-linter/src/rules/ast/camel_case_detector.rs [hunk 14]
```diff
@@ -0,0 +1,260 @@
...
+use std::collections::HashSet;
+use tolk_macros::ViolationMetadata;
+use tolk_resolver::file_index::FileId;
+use tolk_resolver::{Resolved, Symbol, SymbolId};
+
+/// ### What it does
+/// Checks for variables and parameters that are declared but never used.
+///
+/// ### Why is this bad?
+/// Unused variables and parameters clutter the code and can be a sign of a bug.
```
Comment (Danil42Russia) [inline crates/tolk-linter/src/rules/ast/camel_case_detector.rs]: did not expect to see such an effect :D

File: crates/tolk-linter/src/rules/violation.rs (hunk 9 above)
Comment (Danil42Russia) [inline crates/tolk-linter/src/rules/violation.rs]: IMHO, but it seems better not to interfere with error checking and code style  :(
I would give the style rules a separate prefix (let's assume `S`)

File: crates/tolk-linter/src/rules/diagnostic.rs [hunk 15]
```diff
@@ -41,6 +41,7 @@ pub struct Fix {
 pub struct Edit {
     pub span: Span,
     pub replacement: String,
+    pub file_id: Option<FileId>,
```
Comment (i582) [inline crates/tolk-linter/src/rules/diagnostic.rs]: Let's make it mandatory

File: crates/tolk-linter/src/rules/ast/camel_case_detector.rs [hunk 16]
```diff
@@ -0,0 +1,260 @@
...
+            };
+            checker.emit_diagnostic(CamelCaseDetector::rule(), diagnostic);
+        }
+    }
+
+    // globals
+    let globals = checker.type_db.project_index.global_symbols();
+
+    for symbol_name in globals {
+        for symbol_id in symbol_name.1 {
```
Comment (i582) [inline crates/tolk-linter/src/rules/ast/camel_case_detector.rs]: `for symbol_name in globals.values() {`

**Review by i582 — APPROVED** [review]
